<?php
if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Templatemanager extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->library('encrypt');
        $this->load->model('opsi_website');
        $this->load->model('setting_model');
        $this->load->model('permission_model');
    }

    public function index()
    {
        $usr=$this->session->userdata('logged_in');
        $mod=$this->permission_model->get_data_module('templatemanager');
        $per=$this->permission_model->get_data_akses($mod->module_id,$usr['group']);

        if($this->session->userdata('logged_in')) {
            if(!empty($per->is_view)&&($per->is_view=='true')) {
                $datas=$this->opsi_website->getdata();

                $data['id']=$datas->id;
                $data['judul']=$datas->website_title;
                $data['company']=$datas->company_name;
                $data['template']=$datas->template;
                $data['judul_panel']='Pengaturan halaman';                
                
                $this->load->helper('directory');
                $dir="assets/frontend/";
                $map = directory_map($dir);

                $data['dir'] = $dir;
                $data['map'] = $map;

                $view = 'templates/backend/templatemanager_modul/templatemanager_data';
                show($view, $data);
            } else if(empty($per->is_view)) {
                $this->session->set_flashdata('error', 'Maaf, Anda tidak memiliki hak akses!');
                redirect('backend_panel/dashboard', 'refresh');
            } else {
                $this->session->set_flashdata('error', 'Maaf, Anda tidak memiliki hak akses!');
                redirect('backend_panel/dashboard', 'refresh');
            }
        } else {
            redirect('backend_panel', 'refresh');
        }
    }

    public function template_save()
    {
        $template   = $this->input->post('nm_template');
        $id         = $this->input->post('id');
        $dt=array(
                'template' => $template
            );

        $result=$this->setting_model->update_data($id,$dt);
        if($result!=FALSE) {
            $this->session->set_flashdata('success', 'Template berhasil dirubah!');
            redirect('templatemanager', 'refresh');
        } else {
            $this->session->set_flashdata('error', 'Template gagal dirubah!');
            redirect('templatemanager', 'refresh');
        }
    }
}

/* End of file post.php */
/* Location: ./application/controllers/post.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-03-24 05:13:11 */

?>