<?php

$string = "<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class " . $m . " extends CI_Model
{
    public \$table = '$tbl_name';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        \$this->db->select('*');
        \$this->db->from('$tbl_name');

        \$query = \$this->db->get();
        return \$query->result();
    }

    function get_dataall(\$param,\$sampai,\$dari)
    {
        \$this->db->select('*');
        if(\$param['query1']!='') {
            \$this->db->like('name',\$param['query1']);
        }

        \$query = \$this->db->get('$tbl_name',\$sampai,\$dari);
        return \$query->result();
    }

    function jumlah(){
        return \$this->db->get('$tbl_name')->num_rows();
    }

    function get_data_edit(\$id)
    {
        \$this->db->select('*');
        \$this->db->from('$tbl_name');
        \$this->db->where('$primary_f', \$id);

        \$query = \$this->db->get();
        \$result = \$query->row();
        return \$result;
    }

    function save_data(\$data)
    {
        \$query = \$this->db->insert('$tbl_name', \$data);
        return \$query;
    }

    function update_data(\$id,\$data)
    {
        \$this->db->where('$primary_f', \$id);
        return \$this->db->update('$tbl_name', \$data);
    }

    function hapus(\$id)
    {
        \$this->db->where('$primary_f', \$id);
        return \$this->db->delete('$tbl_name');
    }

}

/* End of file $m_file */
/* Location: ./application/models/$m_file */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator ".date('Y-m-d H:i:s')." */
?>";

$target = "application/models/".$m_file;

if ( ! write_file($target, $string)) {
    echo 'Unable to write the model file<br>';
} else {
    echo 'File model written!<br>';
}

?>