<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Bahan_model extends CI_Model
{
    public $table = 'kb_bahan';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        $this->db->select('*');
        $this->db->from('kb_bahan');

        $query = $this->db->get();
        return $query->result();
    }

    function get_dataall($param,$sampai,$dari)
    {
        $this->db->select('*');
        if($param['query1']!='') {
            $this->db->like('name',$param['query1']);
        }

        $query = $this->db->get('kb_bahan',$sampai,$dari);
        return $query->result();
    }

    function jumlah(){
        return $this->db->get('kb_bahan')->num_rows();
    }

    function get_data_edit($id)
    {
        $this->db->select('*');
        $this->db->from('kb_bahan');
        $this->db->where('id_bahan', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function save_data($data)
    {
        $query = $this->db->insert('kb_bahan', $data);
        return $query;
    }

    function update_data($id,$data)
    {
        $this->db->where('id_bahan', $id);
        return $this->db->update('kb_bahan', $data);
    }

    function hapus($id)
    {
        $this->db->where('id_bahan', $id);
        return $this->db->delete('kb_bahan');
    }

}

/* End of file bahan_model.php */
/* Location: ./application/models/bahan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-11-13 12:28:21 */
?>