<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Belanja_model extends CI_Model
{
    public $table = 'kb_products';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        $this->db->select('*');
        $this->db->from('kb_products');

        $query = $this->db->get();
        return $query->result();
    }
    
	function get_kategori(){
		$this->db->select('*');
        $this->db->from('kb_products_category');	
		$this->db->where("is_parent", '1');
        $this->db->where("parent_id", '0');
        $query = $this->db->get();
        return $query->result();
	}

    function get_dataall($param,$sampai,$dari)
    {
        $this->db->select('a.*, b.category as kat, c.category as subkat, d.nama_label, e.harga');
        $this->db->from('kb_products as a');
        if($param['query1']!='') {
            $this->db->like('nama_produk',$param['query1']);
        }
        if($param['status']!='') {
            $this->db->where('status',$param['status']);
        }
        if($param['kategori']!='') {
            $this->db->where('kategori',$param['kategori']);
        }
        $this->db->join('kb_products_category as b', 'a.kategori = b.id_prod_category', 'LEFT');
        $this->db->join('kb_products_category as c', 'a.subkategori = c.id_prod_category', 'LEFT');
        $this->db->join('kb_label_produk as d', 'a.id_label = d.id_label', 'LEFT');
        $this->db->join('kb_products_detail as e', 'a.id_produk = e.id_produk', 'LEFT');
        $this->db->limit($sampai,$dari);
        $query = $this->db->get();
        return $query->result();
    }

    function jumlah($param){
        if($param['query1']!='') {
            $this->db->like('nama_produk',$param['query1']);
        }
        if($param['status']!='') {
            $this->db->where('status',$param['status']);
        }
        if($param['kategori']!='') {
            $this->db->where('kategori',$param['kategori']);
        }
        return $this->db->get('kb_products')->num_rows();
    }

    function get_data_edit($id)
    {
        $this->db->select('*');
        $this->db->from('kb_products');
        $this->db->where('id_produk', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function save_data($data)
    {
        $query = $this->db->insert('kb_products', $data);
        return $query;
    }

    function update_data($id,$data)
    {
        $this->db->where('id_produk', $id);
        return $this->db->update('kb_products', $data);
    }

    function hapus($id)
    {
        $this->db->where('id_produk', $id);
        return $this->db->delete('kb_products');
    }

}

/* End of file belanja_model.php */
/* Location: ./application/models/belanja_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-06-04 12:14:27 */
?>