<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Detailpesanan_model extends CI_Model
{
    public $table = 'kb_belanja_reseller_detail';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        $this->db->select('*');
        $this->db->from('kb_belanja_reseller_detail');

        $query = $this->db->get();
        return $query->result();
    }

    function get_dataall($param,$sampai,$dari,$nofaktur)
    {
        /*
        $this->db->select('*');
        $this->db->where('no_faktur',$nofaktur);
        if($param['query1']!='') {
            $this->db->like('name',$param['query1']);
        }

        $query = $this->db->get('kb_belanja_reseller_detail',$sampai,$dari);
         * 
         */
        $this->db->select('*');
        $this->db->where('no_faktur',$nofaktur);
        return $this->db->get('kb_belanja_reseller_detail', $sampai, $dari)->result();
        //return $query->result();
    }

    function jumlah($nofaktur){
        $this->db->where('no_faktur',$nofaktur);
        return $this->db->get('kb_belanja_reseller_detail')->num_rows();
    }

    function get_data_edit($id)
    {
        $this->db->select('*');
        $this->db->from('kb_belanja_reseller_detail');
        $this->db->where('', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function save_data($data)
    {
        $query = $this->db->insert('kb_belanja_reseller_detail', $data);
        return $query;
    }

    function update_data($id,$data)
    {
        $this->db->where('', $id);
        return $this->db->update('kb_belanja_reseller_detail', $data);
    }

    function hapus($id)
    {
        $this->db->where('', $id);
        return $this->db->delete('kb_belanja_reseller_detail');
    }

}

/* End of file detailpesanan_model.php */
/* Location: ./application/models/detailpesanan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-03-29 11:57:33 */
?>