<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Ekspedisi_model extends CI_Model
{
    public $table = 'kb_jasa_ekspedisi';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        $this->db->select('*');
        $this->db->from('kb_jasa_ekspedisi');

        $query = $this->db->get();
        return $query->result();
    }

    function get_dataall($param,$sampai,$dari)
    {
        $this->db->select('*');
        if($param['query1']!='') {
            $this->db->like('nm_ekspedisi',$param['query1']);
        }

        $query = $this->db->get('kb_jasa_ekspedisi',$sampai,$dari);
        return $query->result();
    }

    function jumlah(){
        return $this->db->get('kb_jasa_ekspedisi')->num_rows();
    }

    function get_data_edit($id)
    {
        $this->db->select('*');
        $this->db->from('kb_jasa_ekspedisi');
        $this->db->where('id_ekspedisi', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function save_data($data)
    {
        $query = $this->db->insert('kb_jasa_ekspedisi', $data);
        return $query;
    }

    function update_data($id,$data)
    {
        $this->db->where('id_ekspedisi', $id);
        return $this->db->update('kb_jasa_ekspedisi', $data);
    }

    function hapus($id)
    {
        $this->db->where('id_ekspedisi', $id);
        return $this->db->delete('kb_jasa_ekspedisi');
    }

}

/* End of file ekspedisi_model.php */
/* Location: ./application/models/ekspedisi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-07-23 13:41:36 */
?>