<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Inputsaldo_model extends CI_Model
{
    public $table = 'kb_isi_ulang_saldo';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        $this->db->select('*');
        $this->db->from('kb_isi_ulang_saldo');

        $query = $this->db->get();
        return $query->result();
    }

    function get_dataall($param,$sampai,$dari)
    {
        $this->db->select('kb_isi_ulang_saldo.*,b.display_name as display_name ,c.display_name as ci');
        if($param['query1']!='') {
            $this->db->like('kb_isi_ulang_saldo.no_tf',$param['query1']);
            $this->db->or_like('kb_isi_ulang_saldo.tgl_tf',$param['query1']);
            $this->db->or_like('kb_isi_ulang_saldo.nominal',$param['query1']);
            $this->db->or_like('b.display_name',$param['query1']);
        }
        $this->db->join('kb_users as b','kb_isi_ulang_saldo.id_reseller = b.id','left');
        $this->db->join('kb_users as c','kb_isi_ulang_saldo.id_admin = c.id','left');
        $query = $this->db->get('kb_isi_ulang_saldo',$sampai,$dari);
        return $query->result();
    }

    function jumlah($param){
        if($param['query1']!='') {
            $this->db->like('kb_isi_ulang_saldo.no_tf',$param['query1']);
            $this->db->or_like('kb_isi_ulang_saldo.tgl_tf',$param['query1']);
            $this->db->or_like('kb_isi_ulang_saldo.nominal',$param['query1']);
            $this->db->or_like('b.display_name',$param['query1']);
        }
        $this->db->join('kb_users as b','kb_isi_ulang_saldo.id_reseller = b.id','left');
        $this->db->join('kb_users as c','kb_isi_ulang_saldo.id_admin = c.id','left');
        return $this->db->get('kb_isi_ulang_saldo')->num_rows();
    }

    function get_data_edit($id)
    {
        $this->db->select('*');
        $this->db->from('kb_isi_ulang_saldo');
        $this->db->where('no_tf', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function save_data($data)
    {
        $query = $this->db->insert('kb_isi_ulang_saldo', $data);
        return $query;
    }

    function update_data($id,$data)
    {
        $this->db->where('no_tf', $id);
        return $this->db->update('kb_isi_ulang_saldo', $data);
    }

    function hapus($id)
    {
        $this->db->where('no_tf', $id);
        return $this->db->delete('kb_isi_ulang_saldo');
    }

}

/* End of file inputsaldo_model.php */
/* Location: ./application/models/inputsaldo_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-03-25 20:09:26 */
?>