<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Konfirmasipesanan_model extends CI_Model
{
    public $table = 'kb_belanja_reseller';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        $this->db->select('*');
        $this->db->from('kb_belanja_reseller');

        $query = $this->db->get();
        return $query->result();
    }

    function get_dataall($param,$sampai,$dari)
    {
        $this->db->select('kb_belanja_reseller.*,kb_users.display_name,b.display_name as admin');
        if($param['query1']!='') {
            $this->db->like('kb_belanja_reseller.no_faktur',$param['query1']);
            $this->db->or_like('kb_belanja_reseller.id_reseller',$param['query1']);
            $this->db->or_like('kb_belanja_reseller.tanggal',$param['query1']);
            $this->db->or_like('kb_belanja_reseller.total_belanja',$param['query1']);
            $this->db->or_like('kb_users.display_name',$param['query1']);
        }
        $this->db->join('kb_users','kb_belanja_reseller.id_reseller = kb_users.id','left');
        $this->db->join('kb_users as b','kb_belanja_reseller.id_admin = b.id','left');
        $query = $this->db->get('kb_belanja_reseller',$sampai,$dari);
        return $query->result();
    }
    
    function getDetail($param,$sampai,$dari,$nofaktur) {
        $this->db->select('kb_belanja_reseller_detail.*, kb_belanja_reseller.*,kb_products.nama_produk');

       
        $this->db->join('kb_belanja_reseller_detail','kb_belanja_reseller.no_faktur=kb_belanja_reseller_detail.no_faktur','left');
        $this->db->join('kb_products','kb_belanja_reseller_detail.id_produk=kb_products.id_produk','left');
        $this->db->order_by('id_admin','desc');
        $this->db->where('kb_belanja_reseller.no_faktur',$nofaktur);
        return $this->db->get('kb_belanja_reseller')->result();
    }

    function jumlah($param){
        if($param['query1']!='') {
            $this->db->like('kb_belanja_reseller.no_faktur',$param['query1']);
            $this->db->or_like('kb_belanja_reseller.id_reseller',$param['query1']);
            $this->db->or_like('kb_belanja_reseller.tanggal',$param['query1']);
            $this->db->or_like('kb_belanja_reseller.total_belanja',$param['query1']);
            $this->db->or_like('kb_users.display_name',$param['query1']);
        }
        $this->db->join('kb_users','kb_belanja_reseller.id_reseller = kb_users.id','left');
        $this->db->join('kb_users as b','kb_belanja_reseller.id_admin = b.id','left');
        return $this->db->get('kb_belanja_reseller')->num_rows();
    }
    

    function get_data_edit($id)
    {
        $this->db->select('*');
        $this->db->from('kb_belanja_reseller');
        $this->db->where('no_faktur', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function save_data($data)
    {
        $query = $this->db->insert('kb_belanja_reseller', $data);
        return $query;
    }
    
    function save_data_detail($data)
    {
        $query = $this->db->insert('kb_belanja_reseller_detail', $data);
        return $query;
    }    

    function update_data($id,$data)
    {
        $this->db->where('no_faktur', $id);
        return $this->db->update('kb_belanja_reseller', $data);
    }

    function hapus($id)
    {
        $this->db->where('no_faktur', $id);
        return $this->db->delete('kb_belanja_reseller');
    }

}

/* End of file konfirmasipesanan_model.php */
/* Location: ./application/models/konfirmasipesanan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-03-29 11:24:54 */
?>