<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Label_produk_model extends CI_Model
{
    public $table = 'kb_label_produk';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        $this->db->select('*');
        $this->db->from('kb_label_produk');

        $query = $this->db->get();
        return $query->result();
    }

    function get_dataall($param,$sampai,$dari)
    {
        $this->db->select('*');
        if($param['query1']!='') {
            $this->db->like('nama_label',$param['query1']);
            $this->db->or_like('id_label',$param['query1']);
        }

        $query = $this->db->get('kb_label_produk',$sampai,$dari);
        return $query->result();
    }

    function jumlah($param){
        if($param['query1']!='') {
            $this->db->like('nama_label',$param['query1']);
            $this->db->or_like('id_label',$param['query1']);
        }
        return $this->db->get('kb_label_produk')->num_rows();
    }

    function get_data_edit($id)
    {
        $this->db->select('*');
        $this->db->from('kb_label_produk');
        $this->db->where('id_label', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function save_data($data)
    {
        $query = $this->db->insert('kb_label_produk', $data);
        return $query;
    }

    function update_data($id,$data)
    {
        $this->db->where('id_label', $id);
        return $this->db->update('kb_label_produk', $data);
    }

    function hapus($id)
    {
        $this->db->where('id_label', $id);
        return $this->db->delete('kb_label_produk');
    }
    

}

/* End of file label_produk_model.php */
/* Location: ./application/models/label_produk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-03-24 05:17:00 */
?>