<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Media_kat_model extends CI_Model
{
    public $table = 'kb_media_type';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        $this->db->select('*');
        $this->db->from('kb_media_type');

        $query = $this->db->get();
        return $query->result();
    }

    function get_dataall($param,$sampai,$dari)
    {
        $this->db->select('kb_media_type.*,kb_user_detail.name');
        if($param['query1']!='') {
            $this->db->like('kb_user_detail.name',$param['query1']);
            $this->db->or_like('id_media_cat',$param['query1']);
            $this->db->or_like('category ',$param['query1']);
        }
        $this->db->join("kb_user_detail","kb_media_type.id_user=kb_user_detail.id","left");
        $query = $this->db->get('kb_media_type',$sampai,$dari);
        return $query->result();
    }

    function jumlah($param){
        if($param['query1']!='') {
            $this->db->like('kb_user_detail.name',$param['query1']);
            $this->db->or_like('id_media_cat',$param['query1']);
            $this->db->or_like('category ',$param['query1']);
        }
        $this->db->join("kb_user_detail","kb_media_type.id_user=kb_user_detail.id","left");
        return $this->db->get('kb_media_type')->num_rows();
    }

    function get_data_edit($id)
    {
        $this->db->select('*');
        $this->db->from('kb_media_type');
        $this->db->where('id_media_cat', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function save_data($data)
    {
        $query = $this->db->insert('kb_media_type', $data);
        return $query;
    }

    function update_data($id,$data)
    {
        $this->db->where('id_media_cat', $id);
        return $this->db->update('kb_media_type', $data);
    }

    function hapus($id)
    {
        $this->db->where('id_media_cat', $id);
        return $this->db->delete('kb_media_type');
    }
    
    function cekkateg($id) {
        $this->db->select('kategori');
        $this->db->from('kb_media');
        $this->db->where('kategori', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

}

/* End of file media_kat.php */
/* Location: ./application/models/media_kat.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-05-13 15:17:08 */
?>