<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Permission_model extends CI_Model
{
    public $table = 'kb_permission';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        $this->db->select('*');
        $this->db->from('kb_permission');

        $query = $this->db->get();
        return $query->result();
    }

    function get_dataall($param,$sampai,$dari)
    {
        $this->db->select('a.id_module, a.id_user_group, a.id as idnya, a.is_view, a.is_add, a.is_edit, a.is_delete, b.type, c.module_title');
        $this->db->join('kb_user_type as b', 'b.id = a.id_user_group', 'LEFT');
        $this->db->join('kb_modules as c', 'c.module_id = a.id_module', 'LEFT');
        if($param['modul']!='') {
            $this->db->where('a.id_module',$param['modul']);
        }
        if($param['grup']!='') {
            $this->db->where('a.id_user_group',$param['grup']);
        }

        $query = $this->db->get('kb_permission as a',$sampai,$dari);
        return $query->result();
    }

    function jumlah($param){
        $this->db->join('kb_user_type as b', 'b.id = a.id_user_group', 'LEFT');
        $this->db->join('kb_modules as c', 'c.module_id = a.id_module', 'LEFT');
        if($param['modul']!='') {
            $this->db->where('a.id_module',$param['modul']);
        }
        if($param['grup']!='') {
            $this->db->where('a.id_user_group',$param['grup']);
        }
        return $this->db->get('kb_permission as a')->num_rows();
    }

    function get_data_edit($id)
    {
        $this->db->select('*');
        $this->db->from('kb_permission');
        $this->db->where('id', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function get_data_cek($idmodule, $idusergrup)
    {
        $this->db->select('*');
        $this->db->from('kb_permission');
        $this->db->where('id_module', $idmodule);
        $this->db->where('id_user_group', $idusergrup);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function get_data_module($name)
    {
        $this->db->select('*');
        $this->db->from('kb_modules');
        $this->db->where('module_name', $name);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function get_data_akses($id,$idgrup)
    {
        $this->db->select('*');
        $this->db->from('kb_permission');
        $this->db->where('id_module', $id);
        $this->db->where('id_user_group', $idgrup);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function save_data($data)
    {
        $query = $this->db->insert('kb_permission', $data);
        return $query;
    }

    function update_data($id,$data)
    {
        $query=$this->db->where('id', $id);
        $query=$this->db->update('kb_permission', $data);
        return $query;
    }

    function hapus($id)
    {
        $this->db->where('id', $id);
        $this->db->delete('kb_permission');
    }

}

/* End of file permission_model.php */
/* Location: ./application/models/permission_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-03-22 14:09:22 */
?>