<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Post_category_model extends CI_Model
{
    public $table = 'kb_post_category';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        $this->db->select('*');
        $this->db->from('kb_post_category');

        $query = $this->db->get();
        return $query->result();
    }
    function get_seo($seo)
    {
        $this->db->select('seo_url');
        $this->db->from('kb_post_category');
        $this->db->where('seo_url', $seo);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }
    
        function cekdata($id) {
        $this->db->select('post_parent');
        $this->db->from('kb_posts');
        $this->db->where('post_parent',$id);
        $query = $this->db->get();
        return $query->result();  
    }
    
    function get_dataall($param,$sampai,$dari)
    {
        $this->db->select('*');
        if($param['query1']!='') {
            $this->db->like('category',$param['query1']);
            $this->db->or_like('seo_url',$param['query1']);
        }

        $query = $this->db->get('kb_post_category',$sampai,$dari);
        return $query->result();
    }

    function jumlah($param){
        if($param['query1']!='') {
            $this->db->like('category',$param['query1']);
            $this->db->or_like('seo_url',$param['query1']);
        }
        return $this->db->get('kb_post_category')->num_rows();
    }

    function get_data_edit($id)
    {
        $this->db->select('*');
        $this->db->from('kb_post_category');
        $this->db->where('post_parent', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function get_name($id)
    {
        $this->db->select('*');
        $this->db->from('kb_post_category');
        $this->db->where('post_parent', $id);

        $query = $this->db->get();
        $result = $query->row();
        echo $result->category;
        //return $result;
    }

    function save_data($data)
    {
        $query = $this->db->insert('kb_post_category', $data);
        return $query;
    }

    function update_data($id,$data)
    {
        $this->db->where('post_parent', $id);
        return $this->db->update('kb_post_category', $data);
    }

    function hapus($id)
    {
        $this->db->where('post_parent', $id);
        return $this->db->delete('kb_post_category');
    }

}

/* End of file post_category_model.php */
/* Location: ./application/models/post_category_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-04-12 10:32:57 */
?>