<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Reseller_type extends CI_Model
{
    public $table = 'kb_reseller_type';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        $this->db->select('*');
        $this->db->from('kb_reseller_type');

        $query = $this->db->get();
        return $query->result();
    }

    function get_dataall($param,$sampai,$dari)
    {
        $this->db->select('*');
        if($param['query1']!='') {
            $this->db->like('id_typereseller',$param['query1']);
            $this->db->or_like('nama_type',$param['query1']);
        }

        $query = $this->db->get('kb_reseller_type',$sampai,$dari);
        return $query->result();
    }

    function jumlah($param){
        if($param['query1']!='') {
            $this->db->like('id_typereseller',$param['query1']);
            $this->db->or_like('nama_type',$param['query1']);
        }
        return $this->db->get('kb_reseller_type')->num_rows();
    }

    function get_data_edit($id)
    {
        $this->db->select('*');
        $this->db->from('kb_reseller_type');
        $this->db->where('id_typereseller', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function save_data($data)
    {
        $query = $this->db->insert('kb_reseller_type', $data);
        return $query;
    }

    function update_data($id,$data)
    {
        $this->db->where('id_typereseller', $id);
        return $this->db->update('kb_reseller_type', $data);
    }

    function hapus($id)
    {
        $this->db->where('id_typereseller', $id);
        return $this->db->delete('kb_reseller_type');
    }

}

/* End of file reseller_type.php */
/* Location: ./application/models/reseller_type.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-03-23 09:54:00 */
?>