<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Template_cetak_model extends CI_Model
{
    public $table = 'kb_model';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        $this->db->select('*');
        $this->db->from('kb_model');

        $query = $this->db->get();
        return $query->result();
    }

    function get_dataall($param,$sampai,$dari)
    {
        $this->db->select('*');
        if($param['query1']!='') {
            $this->db->like('nama',$param['query1']);
        }

        $query = $this->db->get('kb_model',$sampai,$dari);
        return $query->result();
    }

    function get_data_frontend()
    {
        $this->db->select('*');
        $this->db->order_by('id_model', 'desc');
        $query = $this->db->get('kb_model');
        return $query->result();
    }

    function jumlah(){
        return $this->db->get('kb_model')->num_rows();
    }

    function get_data_edit($id)
    {
        $this->db->select('*');
        $this->db->from('kb_model');
        $this->db->where('id_model', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function save_data($data)
    {
        $query = $this->db->insert('kb_model', $data);
        return $query;
    }

    function update_data($id,$data)
    {
        $this->db->where('id_model', $id);
        return $this->db->update('kb_model', $data);
    }

    function hapus($id)
    {
        $this->db->where('id_model', $id);
        return $this->db->delete('kb_model');
    }

}

/* End of file template_cetak_model.php */
/* Location: ./application/models/template_cetak_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-11-18 13:28:50 */
?>