<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Testimonial_model extends CI_Model
{
    public $table = 'kb_testimonial';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        $this->db->select('*');
        $this->db->from('kb_testimonial');

        $query = $this->db->get();
        return $query->result();
    }

    function get_data_widget()
    {
        $this->db->select('*');
        $this->db->from('kb_testimonial');
        $this->db->where('approval','true');
        $this->db->order_by('id_testimonial', 'desc');
        $this->db->limit(2);

        $query = $this->db->get();
        return $query->result();
    }

    function get_dataall($param,$sampai,$dari)
    {
        $this->db->select('*');
        if($param['query1']!='') {
            $this->db->like('name',$param['query1']);
            $this->db->or_like('testimonial',$param['query1']);
            $this->db->or_like('tanggal',$param['query1']);
            $this->db->or_like('judul_id',$param['query1']);
        }

        $query = $this->db->get('kb_testimonial',$sampai,$dari);
        return $query->result();
    }

    function get_dataall_front($param,$sampai,$dari)
    {
        $this->db->select('*');
        if($param['query1']!='') {
            $this->db->like('name',$param['query1']);
            $this->db->or_like('testimonial',$param['query1']);
            $this->db->or_like('tanggal',$param['query1']);
            $this->db->or_like('judul_id',$param['query1']);
        }
        $this->db->where('approval','true');

        $query = $this->db->get('kb_testimonial',$sampai,$dari);
        return $query->result();
    }

    function jumlah($param){
        if($param['query1']!='') {
            $this->db->like('name',$param['query1']);
            $this->db->or_like('testimonial',$param['query1']);
            $this->db->or_like('tanggal',$param['query1']);
            $this->db->or_like('judul_id',$param['query1']);
        }
        return $this->db->get('kb_testimonial')->num_rows();
    }

    function get_data_edit($id)
    {
        $this->db->select('*');
        $this->db->from('kb_testimonial');
        $this->db->where('id_testimonial', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function save_data($data)
    {
        $query = $this->db->insert('kb_testimonial', $data);
        return $query;
    }

    function update_data($id,$data)
    {
        $this->db->where('id_testimonial', $id);
        return $this->db->update('kb_testimonial', $data);
    }

    function hapus($id)
    {
        $this->db->where('id_testimonial', $id);
        return $this->db->delete('kb_testimonial');
    }

}

/* End of file testimonial_model.php */
/* Location: ./application/models/testimonial_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-03-23 02:25:52 */
?>