<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Updatesaldo_model extends CI_Model
{
    public $table = 'kb_saldo_updated';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        $this->db->select('*');
        $this->db->from('kb_saldo_updated');

        $query = $this->db->get();
        return $query->result();
    }
    function get_data_detail($id)
    {
        $this->db->select('*');
        $this->db->from('kb_saldo_updated');
        $this->db->where('id_reseller',$id);
        $query = $this->db->get();
        return $query->result();
    }

    function get_dataall($param,$sampai,$dari)
    {
        $this->db->select('kb_saldo_updated.*,kb_users.display_name');
        if($param['query1']!='') {
            $this->db->like('kb_saldo_updated.id_reseller',$param['query1']);
            $this->db->or_like('kb_saldo_updated.saldo',$param['query1']);
            $this->db->or_like('kb_users.display_name',$param['query1']);
        }
        $this->db->join('kb_users','kb_saldo_updated.id_reseller=kb_users.id','left');
        $query = $this->db->get('kb_saldo_updated',$sampai,$dari);
        return $query->result();
    }

    function jumlah(){
        return $this->db->get('kb_saldo_updated')->num_rows();
    }

    function get_data_edit($id)
    {
        $this->db->select('*');
        $this->db->from('kb_saldo_updated');
        $this->db->where('id_reseller', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function save_data($data)
    {
        $query = $this->db->insert('kb_saldo_updated', $data);
        return $query;
    }

    function update_data($id,$data)
    {
        $this->db->where('id_reseller', $id);
        return $this->db->update('kb_saldo_updated', $data);
    }

    function hapus($id)
    {
        $this->db->where('id_reseller', $id);
        return $this->db->delete('kb_saldo_updated');
    }

}

/* End of file updatesaldo_model.php */
/* Location: ./application/models/updatesaldo_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-03-27 14:40:21 */
?>