<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Website_model extends CI_Model
{
    public $table = 'kb_option';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        $this->db->select('*');
        $this->db->from('kb_option');

        $query = $this->db->get();
        return $query->result();
    }

    function get_dataall($param,$sampai,$dari)
    {
        $this->db->select('*');
        if($param['query1']!='') {
            $this->db->like('name',$param['query1']);
        }

        $query = $this->db->get('kb_option',$sampai,$dari);
        return $query->result();
    }

    function jumlah($param){
                if($param['query1']!='') {
            $this->db->like('name',$param['query1']);
        }
        return $this->db->get('kb_option')->num_rows();
    }

    function get_data_edit($id)
    {
        $this->db->select('*');
        $this->db->from('kb_option');
        $this->db->where('id', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function save_data($data)
    {
        $query = $this->db->insert('kb_option', $data);
        return $query;
    }

    function update_data($id,$data)
    {
        $this->db->where('id', $id);
        return $this->db->update('kb_option', $data);
    }

    function hapus($id)
    {
        $this->db->where('id', $id);
        return $this->db->delete('kb_option');
    }

}

/* End of file website_model.php */
/* Location: ./application/models/website_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-03-29 20:49:05 */
?>