<?php

if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Widgets_model extends CI_Model
{
    public $table = 'kb_widgets';

    function __construct()
    {
        parent::__construct();
    }

    function get_data()
    {
        $this->db->select('*');
        $this->db->from('kb_widgets');

        $query = $this->db->get();
        return $query->result();
    }

    function get_data_filter($type)
    {
        $this->db->select('*');
        $this->db->from('kb_widgets');
        $this->db->where('nm_widget', $type);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function get_dataall($param,$sampai,$dari)
    {
        $this->db->select('*');
        if($param['query1']!='') {
            $this->db->like('nm_widget',$param['query1']);
        }

        $query = $this->db->get('kb_widgets',$sampai,$dari);
        return $query->result();
    }

    function jumlah($param){
                if($param['query1']!='') {
            $this->db->like('nm_widget',$param['query1']);
        }
        return $this->db->get('kb_widgets')->num_rows();
    }

    function get_data_edit($id)
    {
        $this->db->select('*');
        $this->db->from('kb_widgets');
        $this->db->where('id_widget', $id);

        $query = $this->db->get();
        $result = $query->row();
        return $result;
    }

    function save_data($data)
    {
        $query = $this->db->insert('kb_widgets', $data);
        return $query;
    }

    function update_data($id,$data)
    {
        $this->db->where('id_widget', $id);
        return $this->db->update('kb_widgets', $data);
    }

    function hapus($id)
    {
        $this->db->where('id_widget', $id);
        return $this->db->delete('kb_widgets');
    }

}

/* End of file widgets_model.php */
/* Location: ./application/models/widgets_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2016-05-17 10:20:58 */
?>